apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: test-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-server
      containers:
        - name: grafana
          image: grafana/grafana:10.4-ubuntu
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: <GRAFANA_ADMIN_PASSWORD>
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: test-infra
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300