apiVersion: v1
kind: Namespace
metadata:
  name: test-infra

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: test-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      nodeSelector:
        kubernetes.io/hostname: nixos
      containers:
        - name: nats
          image: nats:2.10-alpine
          ports:
            - containerPort: 4222  # client connections
            - containerPort: 8222  # HTTP monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: test-infra
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222